 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/hours", type: :request do
  
  # Hour. As you add validations to Hour, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Hour.create! valid_attributes
      get hours_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      hour = Hour.create! valid_attributes
      get hour_url(hour)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_hour_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      hour = Hour.create! valid_attributes
      get edit_hour_url(hour)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Hour" do
        expect {
          post hours_url, params: { hour: valid_attributes }
        }.to change(Hour, :count).by(1)
      end

      it "redirects to the created hour" do
        post hours_url, params: { hour: valid_attributes }
        expect(response).to redirect_to(hour_url(Hour.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Hour" do
        expect {
          post hours_url, params: { hour: invalid_attributes }
        }.to change(Hour, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post hours_url, params: { hour: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested hour" do
        hour = Hour.create! valid_attributes
        patch hour_url(hour), params: { hour: new_attributes }
        hour.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the hour" do
        hour = Hour.create! valid_attributes
        patch hour_url(hour), params: { hour: new_attributes }
        hour.reload
        expect(response).to redirect_to(hour_url(hour))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        hour = Hour.create! valid_attributes
        patch hour_url(hour), params: { hour: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested hour" do
      hour = Hour.create! valid_attributes
      expect {
        delete hour_url(hour)
      }.to change(Hour, :count).by(-1)
    end

    it "redirects to the hours list" do
      hour = Hour.create! valid_attributes
      delete hour_url(hour)
      expect(response).to redirect_to(hours_url)
    end
  end
end
