default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: topmate_clone_development

  username: postgres
  password: postgres

test:
  <<: *default
  database: topmate_clone_test

  username: postgres
  password: postgres

production:
  <<: *default
  database: topmate_clone_production
  username: topmate_clone
  password: <%= ENV["TOPMATE_CLONE_DATABASE_PASSWORD"] %>
